# Generated by Django 3.0.4 on 2020-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='catname',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
