# Generated by Django 3.0.2 on 2020-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20200403_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pic',
            new_name='picname',
        ),
        migrations.AddField(
            model_name='article',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
